name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies, lint and build
        run: |
          bun install
          bun run lint
          # bun run build FIXME: build is broken
